version: '3.8'

services:
  pg:
    container_name: pg
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    container_name: web
    build: ./devops_proj
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./devops_proj:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=store_db
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_HOST=pg
      - DB_PORT=5432
    depends_on:
      - pg

volumes:
  postgres_data:
    name: store_data